apis = [
    {
        "name": "Reddit",
        "posts": [
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "abc",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "def",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "abc",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "def",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "abc",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "def",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "abc",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "def",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "abc",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "def",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "abc",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "def",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "ghi",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
        ],
    },
    {
        "name": "YouTube",
        "posts": [
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "jkl",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "mno",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
            {
                "title": "abc",
                "image": "https://picsum.photos/200/300",
                "description": "pqr",
                "author_name": "Gero",
                "author_image": "https://picsum.photos/200/300",
            },
        ],
    },
]
